### ISSUE TITLE
Safari session

### ISSUE THREAD

**Issue by Luisquii** [bilgehan-biricik/nextjs-firebase-auth-demo#1]
Your solution is working perfectly if I use chrome. When I test the solution using Safari, for some reason the cookie is deleted during the login process.

I think when you hit the sign-in endpoint works perfectly (the cookie is there), but when it redirects you to the dashboard, it fails finding the current user:

```
// src/app/dashboard/page.tsx

const currentUser = await getCurrentUser();
if (!currentUser) redirect("/sign-in");
```
and what I have realized is that in that point, when validating the current user, the cookie no longer exists.
Any suggestions ?
As I mention, in chrome works perfectly, in safari doesn't. (Exactly the same code)

**Comment by Luisquii** [comment]
Apparently is an issue with Safari when developing. Source: [LINK](https://stackoverflow.com/a/71883080/9749951)

You just need to set `secure: false` on the sign-in api end-point (just for dev purposes, turn it back to true when deploying to prod)

```
cookies().set("__session", sessionCookie, {
    httpOnly: true,
    maxAge: expiresIn,
    secure: false,
  });
```

**Comment by Luisquii** [comment]
Apparently is an issue with Safari when developing. Source: [LINK](https://stackoverflow.com/a/71883080/9749951)

You just need to set `secure: false` on the sign-in api end-point (just for dev purposes, turn it back to true when deploying to prod)

```
cookies().set("__session", sessionCookie, {
    httpOnly: true,
    maxAge: expiresIn,
    secure: false,
  });
```

**Comment by bilgehan-biricik** [comment]
Hi @Luisquii
Thank you for your contribution! I really did not check in Safari but it seems you find a workaround solution to it.

**Comment by mahrufforhad** [comment]
Will the solution compromise the security?

**Comment by Luisquii** [comment]
> Will the solution compromise the security?

@forhadcp It will, this is just for development purposes, when deploying to prod, you must change it back
